config/routes.rb
Rails.application.routes.draw do

  resources :karte_byourekis
  resources :muryos do
  end
  resources :operators
  resources :recommends
  resources :second_categories

  resources :directories do 
    collection do
      get :search
      get :add
      get :thanks
    end 
  end 
  resources :users do 
    collection do
      get :search
    end 
  end 

  root 'recommends#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  establish_connection(:development_cms)
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  belongs_to :prefecture
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  belongs_to :prefecture
  has_one :operator
end

app/models/karte_byoureki.rb
class KarteByoureki < ActiveRecord::Base
end

app/models/muryo.rb
class Muryo < ActiveRecord::Base
  belongs_to :prefecture
  belongs_to :city
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :directory
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  has_many :cities
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base
  belongs_to :directory
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/second_category.rb
class SecondCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
#  before_filter :authenticate_user!
end

app/controllers/muryos_controller.rb
class MuryosController < ApplicationController
  def index
    @lists = Muryo.all
  end

  def new
  end

  def show
    @muryo = Muryo.find(params[:id])
    @directories = Directory.where(tel_sml: @muryo.tel.gsub('-','')).all
    @operators = Operator.where(email: @muryo.email).all
  end

  def edit
    @form = Directory.find(params[:id])
  end

  def update
    @form = Directory.find(params[:id])
    @form.attributes = form_params
    if @user.save
      flash[:alert] = "編集しました" # TODO: 直す
      redirect_to :users
    else
      render :edit
    end
  end

  def search
    @search = Search::SyanaiDirectory.new(params[:search_syanai_directory])
    @lists = @search.matches
      .page(params[:page])
      .per(30)
      .order(:id)
  end

  private

  def form_params
    params.require(:list).permit(:directory_id)
  end

end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @search = Search::SyanaiUser.new
  end

  def new
  end

  def edit
    @form = User.find(params[:id])
  end

  def update
    @form = User.find(params[:id])
    @form.attributes = form_params
    if @user.save
      flash[:alert] = "編集しました" # TODO: 直す
      redirect_to :users
    else
      render :edit
    end
  end

  def search
    @search = Search::SyanaiUser.new(params[:search_syanai_user])
    @lists = @search.matches
      .page(params[:page])
      .per(10)
      .order(:id)
  end

  private

  def form_params
    params.require(:list).permit(:directory_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hosi num

    return '★' if num == 1
    return '★★' if  num == 2
    return '★★★' if  num == 3
    return '★★★★' if  num == 4
    return '★★★★★' if  num == 5
  
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/muryos_helper.rb
module MuryosHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/muryos/edit.html.erb
<h1>Muryos#edit</h1>
<p>Find me in app/views/muryos/edit.html.erb</p>

app/views/muryos/index.html.erb
<!-- Matter -->
<% content_for :title, '無料登録' %>
<table class="table table-bordered">
  <thead>
  <tr>
    <th>id</th>
    <th>施設名</th>
    <th>電話</th>
    <th>住所</th>
    <th>email</th>
    <th>処理日</th>
    <th>管理画面へ</th>
  </tr>
  </thead> 
  <% @lists.each do |list| %>
    <tbody>
      <tr>
        <th><%=list.id %></th>
        <th><%=list.name %></th>
        <th><%=list.tel %></th>
        <th><%=list.address1 %></th>
        <th><%=list.email %></th>
        <th><%=list.copied_at.strftime('%Y-%m-%d') if list.copied_at.present? %></th>
        <th><%= link_to '詳細', muryo_path(list) %></th>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/muryos/show.html.erb
<% content_for :title, @muryo.name %>
<table class="table table-bordered">
    <tr>
      <th>id</th>
      <td><%=@muryo.id %></td>
    </tr>
    <tr>
      <th>施設名</th>
      <td><%=@muryo.name %></td>
    </tr>
    <tr>
      <th>院長名</th>
      <td><%=@muryo.master_name %></td>
    </tr>
    <tr>
      <th>email</th>
      <td><%=@muryo.email %></td>
    </tr>
    <tr>
      <th>TEL</th>
      <td><%=@muryo.tel %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%=@muryo.address1 %></td>
    </tr>
    <tr>
      <th>登録日</th>
      <td><%=@muryo.created_at.strftime('%Y-%m-%d') %></td>
    </tr>
</table>


<% if @operators.count > 0 or @directories.count > 0 %>
<div class="well">
この登録はできません。お客様へ確認をお願いします。
</div>
<% else %>
<%= link_to 'この施設を新規登録する', add_directories_path(muryo_id: @muryo.id), class: "btn btn-default" %>
<% end %>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-6">
          <h2>登録状況(施設)</h2>
            <% if @directories.count > 0 %>
            <p>この電話番号では下記の施設がすでに登録されています。</p>
              <% for d in @directories %>
              <table class="table table-bordered">
                <tr>
                  <th>施設名</th>
                  <td><%=d.name %></td>
                </tr>
                <tr>
                  <th>院長名</th>
                  <td><%=d.master_name %></td>
                </tr>
                <tr>
                  <th>電話番号</th>
                  <td><%=d.tel %></td>
                </tr>
                <tr>
                  <th>管理アカウント</th>
                  <td><%=d.operator.email %></td>
                </tr>
                <tr>
                  <th>管理アカウント</th>
                  <td><%=d.operator.id %></td>
                </tr>
              </table>
              <% end %>
            <% else %>
            <p>この電話番号では登録されておりません。</p>
            <% end %>
        </div>
        <div class="col-lg-6">
          <h2>登録状況(管理アカウント)</h2>
          <% if @operators.count > 0 %>
          <p>このemailでは下記の施設がすでに登録されています。</p>
            <% for o in @operators %>
            <table class="table table-bordered">
              <tr>
                <th>管理アカウント</th>
                <td><%=o.email %></td>
              </tr>
              <tr>
                <th>管理アカウント</th>
                <td><%=o.id %></td>
              </tr>
              <tr>
                <th>施設</th>
                <td><%=link_to o.directory.name, "http://rirakomi.jp/detail/#{o.directory.id}" %></td>
              </tr>
            </table>
            <% end %>
          <% else %>
          <p>この電話番号では登録されておりません。</p>
          <% end %>
       </div>
      </div>