config/routes.rb
Rails.application.routes.draw do

  resources :karte_byourekis
  resources :muryos do
  end
  resources :operators
  resources :recommends
  resources :second_categories

  resources :directories do 
    collection do
      get :search
      get :add
      get :thanks
    end 
  end 
  resources :users do 
    collection do
      get :search
    end 
  end 

  root 'recommends#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  establish_connection(:development_cms)
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  belongs_to :prefecture
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  belongs_to :prefecture
  has_one :operator
end

app/models/karte_byoureki.rb
class KarteByoureki < ActiveRecord::Base
end

app/models/muryo.rb
class Muryo < ActiveRecord::Base
  belongs_to :prefecture
  belongs_to :city
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :directory
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  has_many :cities
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base
  belongs_to :directory
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/second_category.rb
class SecondCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
#  before_filter :authenticate_user!
end

app/controllers/second_categories_controller.rb
class SecondCategoriesController < ApplicationController

  def index
    @lists=SecondCategory.all
  end

  def new
    @form = SecondCategory.new
  end

  def create
    @form = SecondCategory.new(item_params)
    if @form.save
      flash[:alert] = "登録しました" # TODO: 直す
      redirect_to :second_categories
    else
      render :new
    end
  end

  def edit
    @form = SecondCategory.find(params[:id])
  end

  def update
    @form = SecondCategory.find(params[:id])
    @form.attributes = item_params
    if @form.save
      flash[:alert] = "編集しました" # TODO: 直す
      redirect_to :second_categories
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:second_category).permit(:name,:code)
  end
end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hosi num

    return '★' if num == 1
    return '★★' if  num == 2
    return '★★★' if  num == 3
    return '★★★★' if  num == 4
    return '★★★★★' if  num == 5
  
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/muryos_helper.rb
module MuryosHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/second_categories/_registration.html.erb
<div class="form-group">
  <label class="col-lg-2">名称</label>
  <div class="col-lg-5">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <label class="col-lg-2">コード</label>
  <div class="col-lg-5">
    <%= f.text_field :code, class: "form-control" %>
  </div>
</div>

app/views/second_categories/edit.html.erb
<% content_for :title, 'カテゴリー' %>
<%= render "shared/error_messages", model: @form %>
<%= form_for(@form,  :html => { class: "form-horizontal",role: "form" }) do |f| %>
    <%= render 'registration', f: f %>
    <%= f.submit :second_categories, value: '登録', class: 'btn' %>
<% end %>

app/views/second_categories/index.html.erb
<% content_for :title, 'カテゴリー' %>
<%= link_to '新規追加', new_second_category_path, class: "btn btn-default" %>
<table class="table table-bordered">
  <thead>
  <tr>
    <th>id</th>
    <th>名称</th>
    <th>編集</th>
  </tr>
  </thead> 
  <% @lists.each do |item| %>
    <tbody>
      <tr>
        <th><%=item.id %></th>
        <th><%=item.name %></th>
        <th><%= link_to '編集', edit_second_category_path(item),class: "btn btn-default" %></th>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/second_categories/new.html.erb
<%= render "shared/error_messages", model: @form %>
<%= form_for(@form,  :html => { class: "form-horizontal",role: "form" }) do |f| %>
    <%= render 'registration', f: f %>
    <%= f.submit :second_categories, value: '登録', class: 'btn' %>
<% end %>