config/routes.rb
Rails.application.routes.draw do

  resources :karte_byourekis
  resources :muryos do
  end
  resources :operators
  resources :recommends
  resources :second_categories

  resources :directories do 
    collection do
      get :search
      get :add
      get :thanks
    end 
  end 
  resources :users do 
    collection do
      get :search
    end 
  end 

  root 'recommends#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  establish_connection(:development_cms)
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  belongs_to :prefecture
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  belongs_to :prefecture
  has_one :operator
end

app/models/karte_byoureki.rb
class KarteByoureki < ActiveRecord::Base
end

app/models/muryo.rb
class Muryo < ActiveRecord::Base
  belongs_to :prefecture
  belongs_to :city
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :directory
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  has_many :cities
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base
  belongs_to :directory
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/second_category.rb
class SecondCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
#  before_filter :authenticate_user!
end

app/controllers/karte_byourekis_controller.rb
class KarteByourekisController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end
end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hosi num

    return '★' if num == 1
    return '★★' if  num == 2
    return '★★★' if  num == 3
    return '★★★★' if  num == 4
    return '★★★★★' if  num == 5
  
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/karte_byourekis_helper.rb
module KarteByourekisHelper
end

app/helpers/muryos_helper.rb
module MuryosHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/karte_byourekis/edit.html.erb
<h1>KarteByourekis#edit</h1>
<p>Find me in app/views/karte_byourekis/edit.html.erb</p>

app/views/karte_byourekis/index.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>id</th>
    <th>名称</th>
    <th>編集</th>
    <th>削除</th>
  </tr>
  </thead> 
  <% @lists.each do |list| %>
    <tbody>
      <tr>
        <th><%=list.id %></th>
        <th><%=list.name %></th>
        <th><%= link_to '編集', edit_recommend_path(recommend),class: "btn btn-default" %></th>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/karte_byourekis/new.html.erb
<h1>KarteByourekis#new</h1>
<p>Find me in app/views/karte_byourekis/new.html.erb</p>