config/routes.rb
Rails.application.routes.draw do

  resources :karte_byourekis
  resources :muryos do
  end
  resources :operators
  resources :recommends
  resources :second_categories

  resources :directories do 
    collection do
      get :search
      get :add
      get :thanks
    end 
  end 
  resources :users do 
    collection do
      get :search
    end 
  end 

  root 'recommends#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  establish_connection(:development_cms)
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  belongs_to :prefecture
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  belongs_to :prefecture
  has_one :operator
end

app/models/karte_byoureki.rb
class KarteByoureki < ActiveRecord::Base
end

app/models/muryo.rb
class Muryo < ActiveRecord::Base
  belongs_to :prefecture
  belongs_to :city
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :directory
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  has_many :directories
  has_many :muryos
  has_many :cities
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base
  belongs_to :directory
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/second_category.rb
class SecondCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hosi num

    return '★' if num == 1
    return '★★' if  num == 2
    return '★★★' if  num == 3
    return '★★★★' if  num == 4
    return '★★★★★' if  num == 5
  
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/muryos_helper.rb
module MuryosHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= yield(:title).presence %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= stylesheet_link_tag    params[:controller] %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
 
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">りらこみ社内システム</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><%= link_to '無料登録', muryos_path %></li>
            <li><%= link_to 'ユーザー', users_path %></li>
            <li><%= link_to '施設', directories_path %></li>
            <li><%= link_to '投票', recommends_path %></li>
            <li><%= link_to 'カテゴリー', second_categories_path %></li>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">各種マスタ<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'ユーザー',users_path %></li>
                <li><%= link_to '施設',directories_path %></li>
              </ul>
            </li>
            -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= render_breadcrumbs builder: ::SfBreadcrumbsBuilder %>

          <% if notice -%><p class="alert alert-success"><%= notice %></p><% end -%>
          <% if alert -%><p class="alert alert-error"><%= alert %></p><% end -%>
          <div class='page-header'>
            <h1><%= yield(:title).presence %></h1>
          </div>

          <%= yield %>

        </div>
      </div>

    </div><!-- /.container -->

  </body>
</html>

app/views/layouts/nolayout.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title><%= yield(:title).presence %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= stylesheet_link_tag    params[:controller] %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="span12">
          <% if notice -%><p class="alert alert-success"><%= notice %></p><% end -%>
          <% if alert -%><p class="alert alert-error"><%= alert %></p><% end -%>
          <%= yield %>
        </div> <!-- /container -->
      </div> <!-- /container -->
    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_breadcrumbs.html.erb
<% if elements.present? %>
<ul class="breadcrumb" id="">
<li class=""><%= link_to "HOME", root_path %></li>
<% elements.each do |element| %>
  <li class="">
    <% if element.path.present? %>
      <%= link_to element.name, element.path %>
    <% else %>
      <%= element.name %>
    <% end %>
  </li>
<% end %>
</ul>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <% model.errors.keys.each do |attr| %>
      <p><%= model.errors.full_messages_for(attr).first %></p>
    <% end %>
  </div>
<% end %>